server:
  port: 38888
  tomcat:
    accesslog:
      enabled: false
    max-threads: 600
    min-spare-threads: 64
eureka:
  client:
    service-url:
      defaultZone: http://peer1:11111/eureka/,http://peer2:11111/eureka,http://peer3:11111/eureka
logging:
  level:
    root: off
    org.springframework: off
    org.apache.catalina: off
    org.apache.tomcat: off
    com.yql: debug
ons:
  client:
    logRoot: ~/apps/pay-server/ons.log
    logFileMaxIndex: 5
    logLevel: error

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

spring:
  application:
    name: pay-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://yqlpay-db.mysql.rds.aliyuncs.com:3306/pay_server?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&useNewIO=true&autoReconnectForPools=true
    username: sys_pay_server
    password: pay_server01
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    hibernate:
      cache:
        use_query_cache: true
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  #redis:
  #    host: 192.168.0.35
  #    password:
  #    database: 3
  #    port: 6379
  #    pool:
  #      max-active: 50
  #      max-idle: 15
  #      min-idle: 5
  messages:
      basename: ValidationMessages,errors,messages_zh
  cloud:
      bus:
        enabled: false
      stream:
        kafka:
          binder:
            brokers: zk1:9092,zk2:9092,zk3:9092
            zk-nodes: zk1:2181,zk2:2181,zk3:2181
yql:
  password-md5-str: yql-payserver-1221
  #微信appId
  appid: wxd36dd408cb79ea6b
  #商户号
  mchid: 1418256002
  #微信key
  wxKey: wOdzXgWwbwjPEEZoMXWKudytfYvq6iLo
  #微信异步通知
  wxNotifyUrl: https://www.yqlpay.com/pay-server/pay/wx
  #微信支付 body
  wxBody: 零享购-消费
  #阿里异步通知
  aliPayNotifyUrl:
  institution-id: 158974554
  #商户编码
  fyMerid: 0006510F0344064
  #商户密钥
  fyKey: lcdri7e5j5itaqt41ckbixjgkkri6gay
  listenerTopic: YQL_USER_CENTER
  sendMsgTopic: YQL_PAY_SERVER
  openSendMessage: true
  kunlun:
      #支付host
      host:
      #支付uri；
      pay-uri:
      #微信host
      wxHost: https://api.mch.weixin.qq.com
      #微信预付订单uri
      prepayUri: /pay/unifiedorder
      #微信查询订单uri
      wxQuneryUri: /pay/orderquery
      #微信关闭订单uri
      wxCloseUri: /pay/closeorder
      #富友检验银行卡host
      fyCheckHost: https://mpay.fuiou.com:16128
      #富友检查银行卡uri
      checkCardUri: /checkCard/checkCardFour.pay
      #富友代付host
      fyPayForHost: https://fht.fuiou.com
      #富友代付uri
      payForUri: /req.do
      #验证身份证rui
      checkIdUri: /checkInfo/checkIdentity.pay
  mq:
    AccessKey: LTAIukPGqYkArvKd
    SecretKey: uySPaK3rIxN5EuIjF8Rsbdbvxlkvvf
    ONSAddr: http://onsaddr-internal.aliyun.com:8080/rocketmq/nsaddr4client-internal
    producer:
      ProducerId: PID_YQL_PUBLISHER
    consumer:
      ConsumerId: CID_YQL_PAY_SERVICE


