server:
    port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.35:3306/pay_server?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&useNewIO=true&autoReconnectForPools=true
    username: root
    password: nidaye
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-active: 50
    max-wait: 60000
    time-between-eviction-runsMillis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-on-borrow: true
    test-while-idle: true
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    hibernate:
      ddl-auto: update
      cache:
        use_query_cache: true
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  redis:
      host: 192.168.0.35
      password:
      database: 3
      port: 6379
      pool:
        max-active: 50
        max-idle: 15
        min-idle: 5
  messages:
      basename: ValidationMessages,errors,messages_zh

logging:
  log4j.appender.file.encoding: UTF-8
  log4j.appender.A1.File: /home/logs/pay-server.log
  level:
    org.springframework : ERROR
    org.apache.catalina: ERROR
    com.yql.biz: debug

yql:
  password-md5-str: yql-payserver-1221
  order-num-key: order_center:order:number
  #微信appId
  appid: wxd36dd408cb79ea6b
  #商户号
  mchid: 1418256002
  #微信key
  wxKey: wOdzXgWwbwjPEEZoMXWKudytfYvq6iLo
  #微信异步通知
  wxNotifyUrl: http://localhost:8081/pay/wx
  #微信支付 body
  wxBody: 零享购-消费
  #阿里异步通知
  aliPayNotifyUrl: http://localhost:8081/pay/ali_pay
  institution-id: 158974554
  #商户编码
  fyMerid: 0002900F0345178
  #商户密钥
  fyKey: 123456
  listenerTopic: TEST_USER_REGISTER
  sendMsgTopic: TEST_PAY_SERVER
  openSendMessage: true
  kunlun:
      host: http://localhost:8080
      pay-uri: /test?id={id}
      #微信host
      wxHost: https://api.mch.weixin.qq.com
      #微信预付订单uri
      prepayUri: /pay/unifiedorder
      #微信查询订单uri
      wxQuneryUri: /pay/orderquery
      #微信关闭订单uri
      wxCloseUri: /pay/closeorder
      #富友检验银行卡host
      fyCheckHost: http://www-1.fuiou.com:18670
      #富友代付host
      fyPayForHost: http://www-1.fuiou.com:8992/fuMer
      #富友检查银行卡uri
      checkCardUri: /mobile_pay/checkCard/checkCardFour.pay
      #富友代付uri
      payForUri: /req.do
  mq:
    AccessKey: LTAIukPGqYkArvKd
    SecretKey: uySPaK3rIxN5EuIjF8Rsbdbvxlkvvf
    ONSAddr: http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
    producer:
      ProducerId: PID_YQL_PAY_SERVER
    consumer:
      ConsumerId: CID_YQL_PAY_SERVER


