server:
    port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.38:11111/eureka/
  instance:
       prefer-ip-address: true

spring:
  application:
    name: pay-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.35:3306/pay_server?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&useNewIO=true&autoReconnectForPools=true
    username: root
    password: nidaye
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  redis:
      host: 192.168.0.35
      password:
      database: 3
      port: 6379
      pool:
        max-active: 50
        max-idle: 15
        min-idle: 5
  messages:
      basename: ValidationMessages,errors,messages_zh
  cloud:
      bus:
        enabled: false
logging:
  level:
    org.springframework : ERROR
    org.apache.catalina: ERROR
    com.yql.biz: debug

yql:
  password-md5-str: yql-payserver-1221
  order-num-key: order_center:order:number
  #微信appId
  appid: wxd36dd408cb79ea6b
  #商户号
  mchid: 1418256002
  #微信key
  wxKey: wOdzXgWwbwjPEEZoMXWKudytfYvq6iLo
  #微信异步通知
  wxNotifyUrl: http://171.221.202.60:3838/pay-server/pay/wx
  #微信支付 body
  wxBody: 零享购-消费
  #阿里异步通知
  aliPayNotifyUrl:
  #富友支付异步通知
  fyPayNotifyUrl: http://171.221.202.60:3838/pay-server/pay/fy
  #页面跳转URL
  pageNotifyUrl: http://171.221.202.60:3838/pay-server/pay/fy/page-notify-url
  #支付失败URL
  h5reurl: http://171.221.202.60:3838/pay-server/pay/fy/h5reurl
  institution-id: 158974554
  #商户编码
  fyMerid: 0006510F0344064
  #商户B2C/B2B网关支付交易密钥
  fyTradeKey: lcdri7e5j5itaqt41ckbixjgkkri6gay
  #手机快捷支付/银行卡验证/身份认证/企业认证交易密钥
  fyCheckKey: fncp8kegggup2d7zuekw6gkp9dapzthc
  listenerTopic: TEST_USER_REGISTER
  sendMsgTopic: TEST_PAY_SERVER
  openSendMessage: true
  accountListenerTopic: YQL-ORDER-CENTER
  accountListenerTag: PAY-ORDER-RETURN-STATUS
  kunlun:
      host: http://localhost:8080
      pay-uri: /test?id={id}
      #微信host
      wxHost: https://api.mch.weixin.qq.com
      #微信预付订单uri
      prepayUri: /pay/unifiedorder
      #微信查询订单uri
      wxQuneryUri: /pay/orderquery
      #微信关闭订单uri
      wxCloseUri: /pay/closeorder
      #富友检验银行卡host
      fyCheckHost: http://www-1.fuiou.com:18670/mobile_pay
      #富友检验银行卡host
      #fyCheckHost: https://mpay.fuiou.com:16128
      #富友代付host
      #fyPayForHost: http://www-1.fuiou.com:8992/fuMer
      fyPayForHost: https://fht.fuiou.com
      #富友B2C支付
      fyB2CPayHost: http://www-1.fuiou.com:8888/wg1_run
      #富友代付uri
      payForUri: /req.do
      #富友检查银行卡uri
      checkCardUri: /checkCard/checkCardFour.pay
      #验证身份证rui
      checkIdUri: /checkInfo/checkIdentity.pay
      fyPayUri: /smpGate.do
      fyH5PayUri: /h5pay/payAction.pay
      fyCreateOrderUri: /findPay/createOrder.pay
  mq:
    AccessKey: LTAIukPGqYkArvKd
    SecretKey: uySPaK3rIxN5EuIjF8Rsbdbvxlkvvf
    ONSAddr: http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
    producer:
      ProducerId: PID_YQL_PAY_SERVER
    consumer:
      ConsumerId: CID_YQL_PAY_SERVER


